name: Publish

on:
  workflow_call:
    inputs:
      konfig_yaml_dir:
        description: "Path to directory which contains konfig.yaml"
        type: string
        required: true
        default: "."

jobs:
  # Updates submodule SHAs if necessary and prepares for publishing
  pre-publish:
    runs-on: ubuntu-latest
    outputs:
      has_changesets: ${{ steps.detect-changesets.outputs.has_changesets }}
      sdk_submodule_dirs: ${{ steps.sdk-submodules.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Detect changeset files
        id: detect-changesets
        uses: passiv/konfig-workflows/.github/actions/private/detect-changesets@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}

      - name: Install konfig
        if: steps.detect-changesets.outputs.has_changesets == 'false'
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Detect SDK submodules
        if: steps.detect-changesets.outputs.has_changesets == 'false'
        id: sdk-submodules
        uses: passiv/konfig-workflows/.github/actions/private/detect-sdk-submodules@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}

      - name: Get version bump branch name
        id: branch-name
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        uses: passiv/konfig-workflows/.github/actions/private/get-branch-name@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}

      - name: Set git config
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        run: |
          git config --global user.email "passiv-ops@passiv.com"
          git config --global user.name "Passiv Ops"

      - name: Merge submodule version bump PRs
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        env:
          KONFIG_GITHUB_APP_ID: ${{ secrets.KONFIG_GITHUB_APP_ID }}
          KONFIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.KONFIG_GITHUB_APP_PRIVATE_KEY }}
        uses: passiv/konfig-workflows/.github/actions/private/merge-submodule-prs@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}
          sdk_submodule_dirs: ${{ steps.sdk-submodules.outputs.dirs }}
          head: ${{ steps.branch-name.outputs.branch_name }}
          base: ${{ github.ref_name }}

      - name: Update submodule references
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        uses: passiv/konfig-workflows/.github/actions/private/sync-submodules@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}
          sdk_submodule_dirs: ${{ steps.sdk-submodules.outputs.dirs }}
          push_to: ${{ github.ref_name }}

  publish:
    needs: pre-publish
    if: needs.pre-publish.outputs.has_changesets == 'false'
    strategy:
      matrix:
        # TODO: get the languages from the konfig.yaml file
        language: [typescript, python, go, ruby, php, php7, csharp, java]
    uses: passiv/konfig-workflows/.github/workflows/publish-sdk.yaml@main
    with:
      konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}
      language: ${{ matrix.language }}
      sdk_submodule_dirs: ${{ needs.pre-publish.outputs.sdk_submodule_dirs }}
    secrets: inherit
