name: Publish

on:
  workflow_call:
    inputs:
      konfig_yaml_dir:
        description: "Path to directory which contains konfig.yaml"
        type: string
        required: true
        default: "."

jobs:
  # Updates submodule SHAs if necessary and prepares for publishing
  pre-publish:
    runs-on: ubuntu-latest
    outputs:
      has_changesets: ${{ steps.detect-changesets.outputs.has_changesets }}
      sdk_submodule_dirs: ${{ steps.sdk-submodules.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Detect changeset files
        id: detect-changesets
        uses: passiv/konfig-workflows/.github/actions/private/detect-changesets@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}

      - name: Install konfig
        if: steps.detect-changesets.outputs.has_changesets == 'false'
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Detect SDK submodules
        if: steps.detect-changesets.outputs.has_changesets == 'false'
        id: sdk-submodules
        uses: passiv/konfig-workflows/.github/actions/private/detect-sdk-submodules@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}

      - name: Get version bump branch name
        id: branch-name
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        uses: passiv/konfig-workflows/.github/actions/private/get-branch-name@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}

      - name: Set git config
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        run: |
          git config --global user.email "passiv-ops@passiv.com"
          git config --global user.name "Passiv Ops"

      - name: Merge submodule version bump PRs
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        env:
          KONFIG_GITHUB_APP_ID: ${{ secrets.KONFIG_GITHUB_APP_ID }}
          KONFIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.KONFIG_GITHUB_APP_PRIVATE_KEY }}
        uses: passiv/konfig-workflows/.github/actions/private/merge-submodule-prs@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}
          sdk_submodule_dirs: ${{ steps.sdk-submodules.outputs.dirs }}
          head: ${{ steps.branch-name.outputs.branch_name }}
          base: ${{ github.ref_name }}

      - name: Update submodule references
        if: >
          steps.detect-changesets.outputs.has_changesets == 'false' &&
          steps.sdk-submodules.outputs.dirs != ''
        uses: passiv/konfig-workflows/.github/actions/private/sync-submodules@main
        with:
          konfig_yaml_dir: ${{ inputs.konfig_yaml_dir }}
          sdk_submodule_dirs: ${{ steps.sdk-submodules.outputs.dirs }}
          push_to: ${{ github.ref_name }}

  # test:
  #   runs-on: ubuntu-latest
  #   needs: pre-publish
  #   if: needs.pre-publish.outputs.has_changesets == 'false'
  #   container: # runs in docker container
  #     image: konfigdev/test-and-publish:latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}
  #         submodules: true

  #     - name: Install konfig
  #       uses: passiv/konfig-workflows/.github/actions/install-cli@main

  #     - name: Setup test env vars
  #       uses: passiv/konfig-workflows/.github/actions/private/inject-testing-env-vars@main
  #       with:
  #         TEST_ENV: ${{ secrets.TEST_ENV }}

  #     - name: Run tests
  #       uses: nick-fields/retry@v2
  #       with:
  #         timeout_minutes: 15
  #         max_attempts: 3
  #         retry_on: error
  #         command: cd ${{ inputs.konfig_yaml_dir }} && konfig test

  publish-typescript:
    runs-on: ubuntu-latest
    needs: [pre-publish]
    if: needs.pre-publish.outputs.has_changesets == 'false'
    container: # runs in docker container
      image: konfigdev/test-and-publish:latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install konfig
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Set git config
        run: |
          git config --global user.email "passiv-ops@passiv.com"
          git config --global user.name "Passiv Ops"
          repo=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          git config --global --add safe.directory /__w/$repo/$repo

      - name: Setup test env vars
        uses: passiv/konfig-workflows/.github/actions/private/inject-testing-env-vars@main
        with:
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig test -f typescript

      - name: Publish
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig publish --generator typescript --skipTests --tolerateRepublish --skipRemoteCheck --ci

  publish-go:
    runs-on: ubuntu-latest
    needs: [pre-publish]
    if: needs.pre-publish.outputs.has_changesets == 'false'
    container: # runs in docker container
      image: konfigdev/test-and-publish:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install konfig
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Set git config
        run: |
          git config --global user.email "passiv-ops@passiv.com"
          git config --global user.name "Passiv Ops"
          repo=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          git config --global --add safe.directory /__w/$repo/$repo

      - name: Setup test env vars
        uses: passiv/konfig-workflows/.github/actions/private/inject-testing-env-vars@main
        with:
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig test -f go

      - name: Publish
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig publish --generator go --skipTests --tolerateRepublish --skipRemoteCheck --ci

  publish-python:
    runs-on: ubuntu-latest
    needs: [pre-publish]
    if: needs.pre-publish.outputs.has_changesets == 'false'
    container: # runs in docker container
      image: konfigdev/test-and-publish:latest
    env:
      PYPI_TOKEN_1: ${{ secrets.PYPI_TOKEN_1 }}
      PYPI_TOKEN_2: ${{ secrets.PYPI_TOKEN_2 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install konfig
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Set git config
        run: |
          git config --global user.email "passiv-ops@passiv.com"
          git config --global user.name "Passiv Ops"
          repo=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          git config --global --add safe.directory /__w/$repo/$repo

      - name: Setup test env vars
        uses: passiv/konfig-workflows/.github/actions/private/inject-testing-env-vars@main
        with:
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig test -f python

      - name: Publish
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig publish --generator python --skipTests --tolerateRepublish --skipRemoteCheck --ci

  publish-php:
    runs-on: ubuntu-latest
    needs: [pre-publish]
    if: needs.pre-publish.outputs.has_changesets == 'false'
    container: # runs in docker container
      image: konfigdev/test-and-publish:latest
    env:
      PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Install konfig
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Set git config
        run: |
          git config --global user.email "passiv-ops@passiv.com"
          git config --global user.name "Passiv Ops"
          repo=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          git config --global --add safe.directory /__w/$repo/$repo

      # The PHP SDKs are in git submodules
      - name: Set up SSH key for submodule access
        if: needs.pre-publish.outputs.sdk_submodule_dirs != ''
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SUBMODULE_DEPLOY_KEY_PHP }}

      - name: Setup test env vars
        uses: passiv/konfig-workflows/.github/actions/private/inject-testing-env-vars@main
        with:
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig test -f php,php7

      - name: Publish
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig publish --generator php,php7 --skipTests --tolerateRepublish --skipRemoteCheck --ci

  publish-java:
    runs-on: ubuntu-latest
    needs: [pre-publish]
    if: needs.pre-publish.outputs.has_changesets == 'false'
    container: # runs in docker container
      image: konfigdev/test-and-publish:latest
    env:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install konfig
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Set git config
        run: |
          git config --global user.email "passiv-ops@passiv.com"
          git config --global user.name "Passiv Ops"
          repo=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          git config --global --add safe.directory /__w/$repo/$repo

      - name: Setup test env vars
        uses: passiv/konfig-workflows/.github/actions/private/inject-testing-env-vars@main
        with:
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig test -f java

      - name: Setup GPG for signing
        if: env.GPG_PRIVATE_KEY && env.GPG_PASSPHRASE && env.GPG_KEY_ID
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 -d | gpg --batch --passphrase "$GPG_PASSPHRASE" --import
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent
          gpg-connect-agent reloadagent /bye

      - name: Write settings.xml file for Java publishing
        uses: passiv/konfig-workflows/.github/actions/private/write-settings-xml@main
        with:
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          ossrh_username: ${{ secrets.OSSRH_USERNAME }}
          ossrh_password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Publish
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig publish --generator java --skipTests --tolerateRepublish --skipRemoteCheck --ci

  publish-ruby:
    runs-on: ubuntu-latest
    needs: [pre-publish]
    if: needs.pre-publish.outputs.has_changesets == 'false'
    container: # runs in docker container
      image: konfigdev/test-and-publish:latest
    env:
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install konfig
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Set git config
        run: |
          git config --global user.email "passiv-ops@passiv.com"
          git config --global user.name "Passiv Ops"
          repo=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          git config --global --add safe.directory /__w/$repo/$repo

      - name: Setup test env vars
        uses: passiv/konfig-workflows/.github/actions/private/inject-testing-env-vars@main
        with:
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig test -f ruby

      - name: Publish
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig publish --generator ruby --skipTests --tolerateRepublish --skipRemoteCheck --ci

  publish-csharp:
    runs-on: ubuntu-latest
    needs: [pre-publish]
    if: needs.pre-publish.outputs.has_changesets == 'false'
    container: # runs in docker container
      image: konfigdev/test-and-publish:latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Install konfig
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Set git config
        run: |
          git config --global user.email "passiv-ops@passiv.com"
          git config --global user.name "Passiv Ops"
          repo=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          git config --global --add safe.directory /__w/$repo/$repo

      - name: Setup test env vars
        uses: passiv/konfig-workflows/.github/actions/private/inject-testing-env-vars@main
        with:
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig test -f csharp

      - name: Publish
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: cd ${{ inputs.konfig_yaml_dir }} && konfig publish --generator csharp --skipTests --tolerateRepublish --skipRemoteCheck --ci
